language: objective-c
osx_image: xcode8

env:
  - SCHEME=PMKmacOS DESTINATION='platform=OS X'
#  - SCHEME=PMKiOS DESTINATION='platform=iOS Simulator,name=iPhone 6S'

install:
  - if [ "$SCHEME" == "PMKmacOS" ]; then carthage bootstrap --platform Mac; fi

script:
  - set -o pipefail && xcodebuild -scheme $SCHEME -destination "$DESTINATION" test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
